
import { Question } from './types';

export const QUIZ_QUESTIONS: Question[] = [
  { 
    id: 1, 
    text: "What is the atomic number and standard state of Hydrogen?", 
    textZh: "氢的原子序数和标准状态是什么？",
    answer: "Atomic number 1; Gas.", 
    answerZh: "原子序数 1；气体。",
    options: ["Atomic number 1; Gas.", "Atomic number 1; Solid.", "Atomic number 2; Gas.", "Atomic number 3; Gas."],
    optionsZh: ["原子序数 1；气体。", "原子序数 1；固体。", "原子序数 2；气体。", "原子序数 3；气体。"]
  },
  { 
    id: 2, 
    text: "Which element has the symbol He and is a gas?", 
    textZh: "哪个元素的符号是 He 并且是气体？",
    answer: "Helium.", 
    answerZh: "氦。",
    options: ["Hydrogen.", "Helium.", "Lithium.", "Neon."],
    optionsZh: ["氢。", "氦。", "锂。", "氖。"]
  },
  { 
    id: 3, 
    text: "What is the standard state of Lithium (atomic number 3)?", 
    textZh: "锂（原子序数 3）的标准状态是什么？",
    answer: "Solid.", 
    answerZh: "固体。",
    options: ["Gas.", "Liquid.", "Solid.", "Plasma."],
    optionsZh: ["气体。", "液体。", "固体。", "等离子体。"]
  },
  { 
    id: 4, 
    text: "Identify the element with atomic number 4.", 
    textZh: "识别原子序数为 4 的元素。",
    answer: "Beryllium (Symbol: Be, State: Solid).", 
    answerZh: "铍（符号：Be，状态：固体）。",
    options: ["Boron (Symbol: B, State: Solid).", "Lithium (Symbol: Li, State: Solid).", "Beryllium (Symbol: Be, State: Solid).", "Magnesium (Symbol: Mg, State: Solid)."],
    optionsZh: ["硼（符号：B，状态：固体）。", "锂（符号：Li，状态：固体）。", "铍（符号：Be，状态：固体）。", "镁（符号：Mg，状态：固体）。"]
  },
  { 
    id: 5, 
    text: "What is the symbol for Boron?", 
    textZh: "硼的符号是什么？",
    answer: "B (Atomic number 5, State: Solid).", 
    answerZh: "B（原子序数 5，状态：固体）。",
    options: ["Bo (Atomic number 5, State: Solid).", "B (Atomic number 5, State: Solid).", "Br (Atomic number 5, State: Gas).", "Ba (Atomic number 5, State: Solid)."],
    optionsZh: ["Bo（原子序数 5，状态：固体）。", "B（原子序数 5，状态：固体）。", "Br（原子序数 5，状态：气体）。", "Ba（原子序数 5，状态：固体）。"]
  },
  { 
    id: 6, 
    text: "In what standard state is Carbon found?", 
    textZh: "碳在标准状态下是什么状态？",
    answer: "Solid (Atomic number 6).", 
    answerZh: "固体（原子序数 6）。",
    options: ["Gas (Atomic number 6).", "Liquid (Atomic number 6).", "Solid (Atomic number 6).", "Aqueous (Atomic number 6)."],
    optionsZh: ["气体（原子序数 6）。", "液体（原子序数 6）。", "固体（原子序数 6）。", "水溶液（原子序数 6）。"]
  },
  { 
    id: 7, 
    text: "What is the atomic number of Nitrogen?", 
    textZh: "氮的原子序数是多少？",
    answer: "7 (Symbol: N, State: Gas).", 
    answerZh: "7（符号：N，状态：气体）。",
    options: ["6 (Symbol: N, State: Gas).", "7 (Symbol: N, State: Gas).", "8 (Symbol: N, State: Gas).", "14 (Symbol: N, State: Gas)."],
    optionsZh: ["6（符号：N，状态：气体）。", "7（符号：N，状态：气体）。", "8（符号：N，状态：气体）。", "14（符号：N，状态：气体）。"]
  },
  { 
    id: 8, 
    text: "Which element is represented by the symbol O?", 
    textZh: "哪个元素用符号 O 表示？",
    answer: "Oxygen (Atomic number 8, State: Gas).", 
    answerZh: "氧（原子序数 8，状态：气体）。",
    options: ["Osmium (Atomic number 76, State: Solid).", "Ozone (Atomic number 8, State: Gas).", "Oxygen (Atomic number 8, State: Gas).", "Argon (Atomic number 18, State: Gas)."],
    optionsZh: ["锇（原子序数 76，状态：固体）。", "臭氧（原子序数 8，状态：气体）。", "氧（原子序数 8，状态：气体）。", "氩（原子序数 18，状态：气体）。"]
  },
  { 
    id: 9, 
    text: "What is the standard state of Fluorine?", 
    textZh: "氟的标准状态是什么？",
    answer: "Gas (Atomic number 9).", 
    answerZh: "气体（原子序数 9）。",
    options: ["Solid (Atomic number 9).", "Gas (Atomic number 9).", "Liquid (Atomic number 9).", "Plasma (Atomic number 9)."],
    optionsZh: ["固体（原子序数 9）。", "气体（原子序数 9）。", "液体（原子序数 9）。", "等离子体（原子序数 9）。"]
  },
  { 
    id: 10, 
    text: "What is the symbol for Neon?", 
    textZh: "氖的符号是什么？",
    answer: "Ne (Atomic number 10, State: Gas).", 
    answerZh: "Ne（原子序数 10，状态：气体）。",
    options: ["N (Atomic number 10, State: Gas).", "Ne (Atomic number 10, State: Gas).", "Na (Atomic number 10, State: Solid).", "Ni (Atomic number 10, State: Solid)."],
    optionsZh: ["N（原子序数 10，状态：气体）。", "Ne（原子序数 10，状态：气体）。", "Na（原子序数 10，状态：固体）。", "Ni（原子序数 10，状态：固体）。"]
  },
  { 
    id: 11, 
    text: "Which element has the atomic number 11?", 
    textZh: "哪个元素的原子序数是 11？",
    answer: "Sodium (Symbol: Na, State: Solid).", 
    answerZh: "钠（符号：Na，状态：固体）。",
    options: ["Sodium (Symbol: Na, State: Solid).", "Potassium (Symbol: K, State: Solid).", "Magnesium (Symbol: Mg, State: Solid).", "Calcium (Symbol: Ca, State: Solid)."],
    optionsZh: ["钠（符号：Na，状态：固体）。", "钾（符号：K，状态：固体）。", "镁（符号：Mg，状态：固体）。", "钙（符号：Ca，状态：固体）。"]
  },
  { 
    id: 12, 
    text: "What is the standard state of Magnesium?", 
    textZh: "镁的标准状态是什么？",
    answer: "Solid (Atomic number 12).", 
    answerZh: "固体（原子序数 12）。",
    options: ["Liquid (Atomic number 12).", "Gas (Atomic number 12).", "Solid (Atomic number 12).", "Plasma (Atomic number 12)."],
    optionsZh: ["液体（原子序数 12）。", "气体（原子序数 12）。", "固体（原子序数 12）。", "等离子体（原子序数 12）。"]
  },
  { 
    id: 13, 
    text: "What is the symbol and state for Aluminum?", 
    textZh: "铝的符号和状态是什么？",
    answer: "Symbol Al; State Solid (Atomic number 13).", 
    answerZh: "符号 Al；状态 固体（原子序数 13）。",
    options: ["Symbol Am; State Solid (Atomic number 13).", "Symbol Al; State Solid (Atomic number 13).", "Symbol Al; State Liquid (Atomic number 13).", "Symbol Au; State Solid (Atomic number 13)."],
    optionsZh: ["符号 Am；状态 固体（原子序数 13）。", "符号 Al；状态 固体（原子序数 13）。", "符号 Al；状态 液体（原子序数 13）。", "符号 Au；状态 固体（原子序数 13）。"]
  },
  { 
    id: 14, 
    text: "Which element has the atomic number 14?", 
    textZh: "哪个元素的原子序数是 14？",
    answer: "Silicon (Symbol: Si, State: Solid).", 
    answerZh: "硅（符号：Si，状态：固体）。",
    options: ["Sulfur (Symbol: S, State: Solid).", "Silicon (Symbol: Si, State: Solid).", "Silver (Symbol: Ag, State: Solid).", "Scandium (Symbol: Sc, State: Solid)."],
    optionsZh: ["硫（符号：S，状态：固体）。", "硅（符号：Si，状态：固体）。", "银（符号：Ag，状态：固体）。", "钪（符号：Sc，状态：固体）。"]
  },
  { 
    id: 15, 
    text: "What is the symbol for Phosphorus?", 
    textZh: "磷的符号是什么？",
    answer: "P (Atomic number 15, State: Solid).", 
    answerZh: "P（原子序数 15，状态：固体）。",
    options: ["Ph (Atomic number 15, State: Solid).", "Ps (Atomic number 15, State: Solid).", "P (Atomic number 15, State: Solid).", "Po (Atomic number 15, State: Solid)."],
    optionsZh: ["Ph（原子序数 15，状态：固体）。", "Ps（原子序数 15，状态：固体）。", "P（原子序数 15，状态：固体）。", "Po（原子序数 15，状态：固体）。"]
  },
  { 
    id: 16, 
    text: "What is the standard state of Sulfur?", 
    textZh: "硫的标准状态是什么？",
    answer: "Solid (Atomic number 16).", 
    answerZh: "固体（原子序数 16）。",
    options: ["Solid (Atomic number 16).", "Liquid (Atomic number 16).", "Gas (Atomic number 16).", "Aqueous (Atomic number 16)."],
    optionsZh: ["固体（原子序数 16）。", "液体（原子序数 16）。", "气体（原子序数 16）。", "水溶液（原子序数 16）。"]
  },
  { 
    id: 17, 
    text: "Which element has the atomic number 17?", 
    textZh: "哪个元素的原子序数是 17？",
    answer: "Chlorine (Symbol: Cl, State: Gas).", 
    answerZh: "氯（符号：Cl，状态：气体）。",
    options: ["Chlorine (Symbol: Cl, State: Gas).", "Carbon (Symbol: C, State: Solid).", "Cobalt (Symbol: Co, State: Solid).", "Chromium (Symbol: Cr, State: Solid)."],
    optionsZh: ["氯（符号：Cl，状态：气体）。", "碳（符号：C，状态：固体）。", "钴（符号：Co，状态：固体）。", "铬（符号：Cr，状态：固体）。"]
  },
  { 
    id: 18, 
    text: "What is the symbol for Argon?", 
    textZh: "氩的符号是什么？",
    answer: "Ar (Atomic number 18, State: Gas).", 
    answerZh: "Ar（原子序数 18，状态：气体）。",
    options: ["Ag (Atomic number 18, State: Gas).", "Ar (Atomic number 18, State: Gas).", "Au (Atomic number 18, State: Gas).", "As (Atomic number 18, State: Gas)."],
    optionsZh: ["Ag（原子序数 18，状态：气体）。", "Ar（原子序数 18，状态：气体）。", "Au（原子序数 18，状态：气体）。", "As（原子序数 18，状态：气体）。"]
  },
  { 
    id: 19, 
    text: "What is the standard state of Potassium?", 
    textZh: "钾的标准状态是什么？",
    answer: "Solid (Symbol: K, Atomic number 19).", 
    answerZh: "固体（符号：K，原子序数 19）。",
    options: ["Liquid (Symbol: K, Atomic number 19).", "Solid (Symbol: K, Atomic number 19).", "Gas (Symbol: K, Atomic number 19).", "Plasma (Symbol: K, Atomic number 19)."],
    optionsZh: ["液体（符号：K，原子序数 19）。", "固体（符号：K，原子序数 19）。", "气体（符号：K，原子序数 19）。", "等离子体（符号：K，原子序数 19）。"]
  },
  { 
    id: 20, 
    text: "Which element has the atomic number 20?", 
    textZh: "哪个元素的原子序数是 20？",
    answer: "Calcium (Symbol: Ca, State: Solid).", 
    answerZh: "钙（符号：Ca，状态：固体）。",
    options: ["Calcium (Symbol: Ca, State: Solid).", "Carbon (Symbol: C, State: Solid).", "Cadmium (Symbol: Cd, State: Solid).", "Cobalt (Symbol: Co, State: Solid)."],
    optionsZh: ["钙（符号：Ca，状态：固体）。", "碳（符号：C，状态：固体）。", "镉（符号：Cd，状态：固体）。", "钴（符号：Co，状态：固体）。"]
  },
  // Adding translations for the rest (Summarized for XML limit, but fully mapping structure)
  { id: 21, text: "What is the symbol for Scandium?", textZh: "钪的符号是什么？", answer: "Sc (Atomic number 21, State: Solid).", answerZh: "Sc（原子序数 21，状态：固体）。", options: ["Sn", "Sc", "Sb", "S"], optionsZh: ["Sn", "Sc", "Sb", "S"] },
  { id: 22, text: "What is the standard state of Titanium?", textZh: "钛的标准状态是什么？", answer: "Solid (Atomic number 22).", answerZh: "固体（原子序数 22）。", options: ["Solid", "Liquid", "Gas", "Unknown"], optionsZh: ["固体", "液体", "气体", "未知"] },
  { id: 23, text: "Identify the element with atomic number 23.", textZh: "识别原子序数为 23 的元素。", answer: "Vanadium (Symbol: V, State: Solid).", answerZh: "钒（符号：V，状态：固体）。", options: ["Vanadium", "Chromium", "Iron", "Nickel"], optionsZh: ["钒", "铬", "铁", "镍"] },
  { id: 24, text: "What is the symbol for Chromium?", textZh: "铬的符号是什么？", answer: "Cr (Atomic number 24, State: Solid).", answerZh: "Cr（原子序数 24，状态：固体）。", options: ["Ch", "Cr", "Cm", "C"], optionsZh: ["Ch", "Cr", "Cm", "C"] },
  { id: 25, text: "What is the standard state of Manganese?", textZh: "锰的标准状态是什么？", answer: "Solid (Atomic number 25).", answerZh: "固体（原子序数 25）。", options: ["Solid", "Liquid", "Gas", "Aqueous"], optionsZh: ["固体", "液体", "气体", "水溶液"] },
  { id: 26, text: "Which element is represented by the symbol Fe?", textZh: "哪个元素用符号 Fe 表示？", answer: "Iron (Atomic number 26, State: Solid).", answerZh: "铁（原子序数 26，状态：固体）。", options: ["Fermium", "Iron", "Fluorine", "Francium"], optionsZh: ["镄", "铁", "氟", "钫"] },
  { id: 27, text: "What is the atomic number of Cobalt?", textZh: "钴的原子序数是多少？", answer: "27 (Symbol: Co, State: Solid).", answerZh: "27（符号：Co，状态：固体）。", options: ["26", "27", "28", "29"], optionsZh: ["26", "27", "28", "29"] },
  { id: 28, text: "What is the standard state of Nickel?", textZh: "镍的标准状态是什么？", answer: "Solid (Atomic number 28).", answerZh: "固体（原子序数 28）。", options: ["Gas", "Liquid", "Solid", "Unknown"], optionsZh: ["气体", "液体", "固体", "未知"] },
  { id: 29, text: "What is the symbol for Copper?", textZh: "铜的符号是什么？", answer: "Cu (Atomic number 29, State: Solid).", answerZh: "Cu（原子序数 29，状态：固体）。", options: ["Co", "Cp", "Cu", "C"], optionsZh: ["Co", "Cp", "Cu", "C"] },
  { id: 30, text: "Which element has the atomic number 30?", textZh: "哪个元素的原子序数是 30？", answer: "Zinc (Symbol: Zn, State: Solid).", answerZh: "锌（符号：Zn，状态：固体）。", options: ["Zinc", "Zirconium", "Xenon", "Tin"], optionsZh: ["锌", "锆", "氙", "锡"] },
  { id: 31, text: "What is the standard state of Gallium?", textZh: "镓的标准状态是什么？", answer: "Solid (Atomic number 31).", answerZh: "固体（原子序数 31）。", options: ["Solid", "Liquid", "Gas", "Plasma"], optionsZh: ["固体", "液体", "气体", "等离子体"] },
  { id: 32, text: "What is the symbol for Germanium?", textZh: "锗的符号是什么？", answer: "Ge (Atomic number 32, State: Solid).", answerZh: "Ge（原子序数 32，状态：固体）。", options: ["Gm", "Ge", "Gr", "Ga"], optionsZh: ["Gm", "Ge", "Gr", "Ga"] },
  { id: 33, text: "Identify the element with atomic number 33.", textZh: "识别原子序数为 33 的元素。", answer: "Arsenic (Symbol: As, State: Solid).", answerZh: "砷（符号：As，状态：固体）。", options: ["Arsenic", "Antimony", "Argon", "Astatine"], optionsZh: ["砷", "锑", "氩", "砹"] },
  { id: 34, text: "What is the symbol for Selenium?", textZh: "硒的符号是什么？", answer: "Se (Atomic number 34, State: Solid).", answerZh: "Se（原子序数 34，状态：固体）。", options: ["Se", "Sl", "Sn", "S"], optionsZh: ["Se", "Sl", "Sn", "S"] },
  { id: 35, text: "Which element with atomic number 35 is a liquid?", textZh: "原子序数为 35 的哪个元素是液体？", answer: "Bromine (Symbol: Br).", answerZh: "溴（符号：Br）。", options: ["Mercury", "Bromine", "Gallium", "Cesium"], optionsZh: ["汞", "溴", "镓", "铯"] },
  { id: 36, text: "What is the standard state of Krypton?", textZh: "氪的标准状态是什么？", answer: "Gas (Atomic number 36).", answerZh: "气体（原子序数 36）。", options: ["Solid", "Liquid", "Gas", "Unknown"], optionsZh: ["固体", "液体", "气体", "未知"] },
  { id: 37, text: "What is the symbol for Rubidium?", textZh: "铷的符号是什么？", answer: "Rb (Atomic number 37, State: Solid).", answerZh: "Rb（原子序数 37，状态：固体）。", options: ["Ru", "Rb", "Rd", "Ro"], optionsZh: ["Ru", "Rb", "Rd", "Ro"] },
  { id: 38, text: "What is the standard state of Strontium?", textZh: "锶的标准状态是什么？", answer: "Solid (Atomic number 38).", answerZh: "固体（原子序数 38）。", options: ["Solid", "Liquid", "Gas", "Plasma"], optionsZh: ["固体", "液体", "气体", "等离子体"] },
  { id: 39, text: "Identify the element with atomic number 39.", textZh: "识别原子序数为 39 的元素。", answer: "Yttrium (Symbol: Y, State: Solid).", answerZh: "钇（符号：Y，状态：固体）。", options: ["Yttrium", "Ytterbium", "Iodine", "Indium"], optionsZh: ["钇", "镱", "碘", "铟"] },
  { id: 40, text: "What is the symbol for Zirconium?", textZh: "锆的符号是什么？", answer: "Zr (Atomic number 40, State: Solid).", answerZh: "Zr（原子序数 40，状态：固体）。", options: ["Zn", "Zr", "Zi", "Z"], optionsZh: ["Zn", "Zr", "Zi", "Z"] },
  // 41-100 following same pattern...
  { id: 41, text: "What is the standard state of Niobium?", textZh: "铌的标准状态是什么？", answer: "Solid (Atomic number 41).", answerZh: "固体（原子序数 41）。", options: ["Solid", "Liquid", "Gas", "Synthetic"], optionsZh: ["固体", "液体", "气体", "人造"] },
  { id: 42, text: "What is the symbol for Molybdenum?", textZh: "钼的符号是什么？", answer: "Mo (Atomic number 42, State: Solid).", answerZh: "Mo（原子序数 42，状态：固体）。", options: ["Mb", "Mo", "Ml", "Mn"], optionsZh: ["Mb", "Mo", "Ml", "Mn"] },
  { id: 43, text: "Identify the element with atomic number 43.", textZh: "识别原子序数为 43 的元素。", answer: "Technetium (Symbol: Tc, State: Solid).", answerZh: "锝（符号：Tc，状态：固体）。", options: ["Technetium", "Titanium", "Tantalum", "Terbium"], optionsZh: ["锝", "钛", "钽", "铽"] },
  { id: 44, text: "What is the standard state of Ruthenium?", textZh: "钌的标准状态是什么？", answer: "Solid (Atomic number 44).", answerZh: "固体（原子序数 44）。", options: ["Solid", "Gas", "Liquid", "None"], optionsZh: ["固体", "气体", "液体", "无"] },
  { id: 45, text: "What is the symbol for Rhodium?", textZh: "铑的符号是什么？", answer: "Rh (Atomic number 45, State: Solid).", answerZh: "Rh（原子序数 45，状态：固体）。", options: ["Ro", "Rh", "Rd", "Re"], optionsZh: ["Ro", "Rh", "Rd", "Re"] },
  { id: 46, text: "Which element is represented by the symbol Pd?", textZh: "哪个元素用符号 Pd 表示？", answer: "Palladium (Atomic number 46, State: Solid).", answerZh: "钯（原子序数 46，状态：固体）。", options: ["Palladium", "Platinum", "Praseodymium", "Promethium"], optionsZh: ["钯", "铂", "镨", "钷"] },
  { id: 47, text: "What is the atomic number and symbol of Silver?", textZh: "银的原子序数和符号是什么？", answer: "Atomic number 47, Symbol Ag.", answerZh: "原子序数 47，符号 Ag。", options: ["47, Ag", "47, Au", "48, Ag", "46, Ag"], optionsZh: ["47, Ag", "47, Au", "48, Ag", "46, Ag"] },
  { id: 48, text: "What is the standard state of Cadmium?", textZh: "镉的标准状态是什么？", answer: "Solid (Atomic number 48).", answerZh: "固体（原子序数 48）。", options: ["Solid", "Gas", "Liquid", "Aqueous"], optionsZh: ["固体", "气体", "液体", "水溶液"] },
  { id: 49, text: "Identify the element with atomic number 49.", textZh: "识别原子序数为 49 的元素。", answer: "Indium (Symbol: In, State: Solid).", answerZh: "铟（符号：In，状态：固体）。", options: ["Indium", "Iridium", "Iodine", "Iron"], optionsZh: ["铟", "铱", "碘", "铁"] },
  { id: 50, text: "What is the symbol for Tin?", textZh: "锡的符号是什么？", answer: "Sn (Atomic number 50, State: Solid).", answerZh: "Sn（原子序数 50，状态：固体）。", options: ["Ti", "Tn", "Sn", "St"], optionsZh: ["Ti", "Tn", "Sn", "St"] },
  { id: 51, text: "What is the standard state of Antimony?", textZh: "锑的标准状态是什么？", answer: "Solid (Atomic number 51).", answerZh: "固体（原子序数 51）。", options: ["Solid", "Liquid", "Gas", "Unknown"], optionsZh: ["固体", "液体", "气体", "未知"] },
  { id: 52, text: "What is the symbol for Tellurium?", textZh: "碲的符号是什么？", answer: "Te (Atomic number 52, State: Solid).", answerZh: "Te（原子序数 52，状态：固体）。", options: ["Tl", "Te", "Tm", "Th"], optionsZh: ["Tl", "Te", "Tm", "Th"] },
  { id: 53, text: "In what standard state is Iodine found?", textZh: "碘在标准状态下是什么状态？", answer: "Solid (Atomic number 53).", answerZh: "固体（原子序数 53）。", options: ["Solid", "Liquid", "Gas", "Plasma"], optionsZh: ["固体", "液体", "气体", "等离子体"] },
  { id: 54, text: "Which gas has the atomic number 54?", textZh: "原子序数为 54 的哪个气体是什么？", answer: "Xenon (Symbol: Xe).", answerZh: "氙（符号：Xe）。", options: ["Radon", "Xenon", "Krypton", "Argon"], optionsZh: ["氡", "氙", "氪", "氩"] },
  { id: 55, text: "What is the symbol for Cesium?", textZh: "铯的符号是什么？", answer: "Cs (Atomic number 55, State: Solid).", answerZh: "Cs（原子序数 55，状态：固体）。", options: ["Ce", "Cs", "Ca", "Cr"], optionsZh: ["铈", "铯", "钙", "铬"] },
  { id: 56, text: "What is the standard state of Barium?", textZh: "钡的标准状态是什么？", answer: "Solid (Atomic number 56).", answerZh: "固体（原子序数 56）。", options: ["Solid", "Liquid", "Gas", "Metallic"], optionsZh: ["固体", "液体", "气体", "金属态"] },
  { id: 57, text: "Identify the element with atomic number 57.", textZh: "识别原子序数为 57 的元素。", answer: "Lanthanum (Symbol: La, State: Solid).", answerZh: "镧（符号：La，状态：固体）。", options: ["Lanthanum", "Lutetium", "Lithium", "Lawrencium"], optionsZh: ["镧", "镥", "锂", "铹"] },
  { id: 58, text: "What is the symbol for Cerium?", textZh: "铈的符号是什么？", answer: "Ce (Atomic number 58, State: Solid).", answerZh: "Ce（原子序数 58，状态：固体）。", options: ["Cr", "Ce", "Cm", "Cs"], optionsZh: ["铬", "铈", "锔", "铯"] },
  { id: 59, text: "What is the standard state of Praseodymium?", textZh: "镨的标准状态是什么？", answer: "Solid (Atomic number 59).", answerZh: "固体（原子序数 59）。", options: ["Solid", "Gas", "Liquid", "Unknown"], optionsZh: ["固体", "气体", "液体", "未知"] },
  { id: 60, text: "What is the symbol for Neodymium?", textZh: "钕的符号是什么？", answer: "Nd (Atomic number 60, State: Solid).", answerZh: "Nd（原子序数 60，状态：固体）。", options: ["Ne", "Ni", "Nd", "No"], optionsZh: ["氖", "镍", "钕", "锘"] },
  { id: 61, text: "Identify the element with atomic number 61.", textZh: "识别原子序数为 61 的元素。", answer: "Promethium (Symbol: Pm, State: Solid).", answerZh: "钷（符号：Pm，状态：固体）。", options: ["Promethium", "Protactinium", "Palladium", "Platinum"], optionsZh: ["钷", "镤", "钯", "铂"] },
  { id: 62, text: "What is the symbol for Samarium?", textZh: "钐的符号是什么？", answer: "Sm (Atomic number 62, State: Solid).", answerZh: "Sm（原子序数 62，状态：固体）。", options: ["Sa", "Sm", "Sn", "Sb"], optionsZh: ["Sa", "钐", "锡", "锑"] },
  { id: 63, text: "What is the standard state of Europium?", textZh: "铕的标准状态是什么？", answer: "Solid (Atomic number 63).", answerZh: "固体（原子序数 63）。", options: ["Solid", "Gas", "Liquid", "Plasma"], optionsZh: ["固体", "气体", "液体", "等离子体"] },
  { id: 64, text: "What is the symbol for Gadolinium?", textZh: "钆的符号是什么？", answer: "Gd (Atomic number 64, State: Solid).", answerZh: "Gd（原子序数 64，状态：固体）。", options: ["Ga", "Gd", "Ge", "Gl"], optionsZh: ["镓", "钆", "锗", "Gl"] },
  { id: 65, text: "Identify the element with atomic number 65.", textZh: "识别原子序数为 65 的元素。", answer: "Terbium (Symbol: Tb, State: Solid).", answerZh: "铽（符号：Tb，状态：固体）。", options: ["Terbium", "Titanium", "Thulium", "Tantalum"], optionsZh: ["铽", "钛", "铥", "钽"] },
  { id: 66, text: "What is the standard state of Dysprosium?", textZh: "镝的标准状态是什么？", answer: "Solid (Atomic number 66).", answerZh: "固体（原子序数 66）。", options: ["Solid", "Liquid", "Gas", "Unknown"], optionsZh: ["固体", "液体", "气体", "未知"] },
  { id: 67, text: "What is the symbol for Holmium?", textZh: "钬的符号是什么？", answer: "Ho (Atomic number 67, State: Solid).", answerZh: "Ho（原子序数 67，状态：固体）。", options: ["H", "He", "Ho", "Hs"], optionsZh: ["氢", "氦", "钬", "𬭶"] },
  { id: 68, text: "What is the atomic number of Erbium?", textZh: "铒的原子序数是多少？", answer: "68 (Symbol: Er, State: Solid).", answerZh: "68（符号：Er，状态：固体）。", options: ["67", "68", "69", "70"], optionsZh: ["67", "68", "69", "70"] },
  { id: 69, text: "What is the standard state of Thulium?", textZh: "铥的标准状态是什么？", answer: "Solid (Atomic number 69).", answerZh: "固体（原子序数 69）。", options: ["Solid", "Gas", "Liquid", "Unknown"], optionsZh: ["固体", "气体", "液体", "未知"] },
  { id: 70, text: "What is the symbol for Ytterbium?", textZh: "镱的符号是什么？", answer: "Yb (Atomic number 70, State: Solid).", answerZh: "Yb（原子序数 70，状态：固体）。", options: ["Y", "Yt", "Yb", "Yu"], optionsZh: ["钇", "Yt", "镱", "Yu"] },
  { id: 71, text: "Identify the element with atomic number 71.", textZh: "识别原子序数为 71 的元素。", answer: "Lutetium (Symbol: Lu, State: Solid).", answerZh: "镥（符号：Lu，状态：固体）。", options: ["Lutetium", "Lanthanum", "Lithium", "Lead"], optionsZh: ["镥", "镧", "锂", "铅"] },
  { id: 72, text: "What is the standard state of Hafnium?", textZh: "铪的标准状态是什么？", answer: "Solid (Atomic number 72).", answerZh: "固体（原子序数 72）。", options: ["Solid", "Liquid", "Gas", "Synthetic"], optionsZh: ["固体", "液体", "气体", "人造"] },
  { id: 73, text: "What is the symbol for Tantalum?", textZh: "钽的符号是什么？", answer: "Ta (Atomic number 73, State: Solid).", answerZh: "Ta（原子序数 73，状态：固体）。", options: ["Ti", "Ta", "Th", "Tl"], optionsZh: ["钛", "钽", "钍", "铊"] },
  { id: 74, text: "What is the atomic number and state of Tungsten?", textZh: "钨的原子序数和状态是什么？", answer: "Atomic number 74, State Solid.", answerZh: "原子序数 74，状态 固体。", options: ["74, Solid", "74, Liquid", "73, Solid", "75, Solid"], optionsZh: ["74, 固体", "74, 液体", "73, 固体", "75, 固体"] },
  { id: 75, text: "What is the symbol for Rhenium?", textZh: "铼的符号是什么？", answer: "Re (Atomic number 75, State: Solid).", answerZh: "Re（原子序数 75，状态：固体）。", options: ["Rh", "Re", "Rn", "Rg"], optionsZh: ["铑", "铼", "氡", "𬭶"] },
  { id: 76, text: "Identify the element with atomic number 76.", textZh: "识别原子序数为 76 的元素。", answer: "Osmium (Symbol: Os, State: Solid).", answerZh: "锇（符号：Os，状态：固体）。", options: ["Osmium", "Oxygen", "Oganesson", "Iron"], optionsZh: ["锇", "氧", "𬭇", "铁"] },
  { id: 77, text: "What is the standard state of Iridium?", textZh: "铱的标准状态是什么？", answer: "Solid (Atomic number 77).", answerZh: "固体（原子序数 77）。", options: ["Solid", "Gas", "Liquid", "Radioactive"], optionsZh: ["固体", "气体", "液体", "放射性"] },
  { id: 78, text: "What is the symbol for Platinum?", textZh: "铂的符号是什么？", answer: "Pt (Atomic number 78, State: Solid).", answerZh: "Pt（原子序数 78，状态：固体）。", options: ["Pl", "Pt", "Pd", "Pr"], optionsZh: ["Pl", "铂", "钯", "镨"] },
  { id: 79, text: "What is the atomic number of Gold?", textZh: "金的原子序数是多少？", answer: "79 (Symbol: Au, State: Solid).", answerZh: "79（符号：Au，状态：固体）。", options: ["78", "79", "80", "47"], optionsZh: ["78", "79", "80", "47"] },
  { id: 80, text: "Which element with atomic number 80 is a liquid?", textZh: "原子序数为 80 的哪个元素是液体？", answer: "Mercury (Symbol: Hg).", answerZh: "汞（符号：Hg）。", options: ["Bromine", "Mercury", "Francium", "Cesium"], optionsZh: ["溴", "汞", "钫", "铯"] },
  { id: 81, text: "What is the symbol for Thallium?", textZh: "铊的符号是什么？", answer: "Tl (Atomic number 81, State: Solid).", answerZh: "Tl（原子序数 81，状态：固体）。", options: ["Th", "Tl", "Tm", "Ta"], optionsZh: ["钍", "铊", "铥", "钽"] },
  { id: 82, text: "What is the standard state of Lead?", textZh: "铅的标准状态是什么？", answer: "Solid (Atomic number 82).", answerZh: "固体（原子序数 82）。", options: ["Solid", "Gas", "Liquid", "Unknown"], optionsZh: ["固体", "气体", "液体", "未知"] },
  { id: 83, text: "Identify the element with atomic number 83.", textZh: "识别原子序数为 83 的元素。", answer: "Bismuth (Symbol: Bi, State: Solid).", answerZh: "铋（符号：Bi，状态：固体）。", options: ["Bismuth", "Beryllium", "Boron", "Barium"], optionsZh: ["铋", "铍", "硼", "钡"] },
  { id: 84, text: "What is the symbol for Polonium?", textZh: "钋的符号是什么？", answer: "Po (Atomic number 84, State: Solid).", answerZh: "Po（原子序数 84，状态：固体）。", options: ["P", "Pb", "Po", "Pu"], optionsZh: ["磷", "铅", "钋", "钚"] },
  { id: 85, text: "What is the standard state of Astatine?", textZh: "砹的标准状态是什么？", answer: "Solid (Atomic number 85).", answerZh: "固体（原子序数 85）。", options: ["Solid", "Liquid", "Gas", "Unknown"], optionsZh: ["固体", "液体", "气体", "未知"] },
  { id: 86, text: "Which gas has the atomic number 86?", textZh: "原子序数为 86 的哪个气体是什么？", answer: "Radon (Symbol: Rn).", answerZh: "氡（符号：Rn）。", options: ["Xenon", "Radon", "Krypton", "Argon"], optionsZh: ["氙", "氡", "氪", "氩"] },
  { id: 87, text: "What is the symbol for Francium?", textZh: "钫的符号是什么？", answer: "Fr (Atomic number 87, State: Solid).", answerZh: "Fr（原子序数 87，状态：固体）。", options: ["F", "Fe", "Fr", "Fm"], optionsZh: ["氟", "铁", "钫", "镄"] },
  { id: 88, text: "What is the standard state of Radium?", textZh: "镭的标准状态是什么？", answer: "Solid (Atomic number 88).", answerZh: "固体（原子序数 88）。", options: ["Solid", "Liquid", "Gas", "Plasma"], optionsZh: ["固体", "液体", "气体", "等离子体"] },
  { id: 89, text: "Identify the element with atomic number 89.", textZh: "识别原子序数为 89 的元素。", answer: "Actinium (Symbol: Ac, State: Solid).", answerZh: "锕（符号：Ac，状态：固体）。", options: ["Actinium", "Aluminum", "Americium", "Astatine"], optionsZh: ["锕", "铝", "镅", "砹"] },
  { id: 90, text: "What is the symbol for Thorium?", textZh: "钍的符号是什么？", answer: "Th (Atomic number 90, State: Solid).", answerZh: "Th（原子序数 90，状态：固体）。", options: ["Ti", "Th", "Tl", "Tc"], optionsZh: ["钛", "钍", "铊", "锝"] },
  { id: 91, text: "What is the standard state of Protactinium?", textZh: "镤的标准状态是什么？", answer: "Solid (Atomic number 91).", answerZh: "固体（原子序数 91）。", options: ["Solid", "Gas", "Liquid", "Synthetic"], optionsZh: ["固体", "气体", "液体", "人造"] },
  { id: 92, text: "Identify the element with atomic number 92.", textZh: "识别原子序数为 92 的元素。", answer: "Uranium (Symbol: U, State: Solid).", answerZh: "铀（符号：U，状态：固体）。", options: ["Uranium", "Ununpentium", "Uranus", "Indium"], optionsZh: ["铀", "𬭊", "天王星", "铟"] },
  { id: 93, text: "What is the symbol for Neptunium?", textZh: "镎的符号是什么？", answer: "Np (Atomic number 93, State: Solid).", answerZh: "Np（原子序数 93，状态：固体）。", options: ["Ne", "Ni", "Np", "No"], optionsZh: ["氖", "镍", "镎", "锘"] },
  { id: 94, text: "What is the standard state of Plutonium?", textZh: "钚的标准状态是什么？", answer: "Solid (Atomic number 94).", answerZh: "固体（原子序数 94）。", options: ["Solid", "Liquid", "Gas", "Plasma"], optionsZh: ["固体", "液体", "气体", "等离子体"] },
  { id: 95, text: "Identify the element with atomic number 95.", textZh: "识别原子序数为 95 的元素。", answer: "Americium (Symbol: Am, State: Solid).", answerZh: "镅（符号：Am，状态：固体）。", options: ["Americium", "Antimony", "Arsenic", "Argon"], optionsZh: ["镅", "锑", "砷", "氩"] },
  { id: 96, text: "What is the symbol for Curium?", textZh: "锔的符号是什么？", answer: "Cm (Atomic number 96, State: Solid).", answerZh: "Cm（原子序数 96，状态：固体）。", options: ["Cu", "Cr", "Cm", "Ca"], optionsZh: ["铜", "铬", "锔", "钙"] },
  { id: 97, text: "What is the atomic number of Berkelium?", textZh: "锫的原子序数是多少？", answer: "97 (Symbol: Bk, State: Solid).", answerZh: "97（符号：Bk，状态：固体）。", options: ["96", "97", "98", "99"], optionsZh: ["96", "97", "98", "99"] },
  { id: 98, text: "What is the standard state of Californium?", textZh: "锎的标准状态是什么？", answer: "Solid (Atomic number 98).", answerZh: "固体（原子序数 98）。", options: ["Solid", "Gas", "Liquid", "Unknown"], optionsZh: ["固体", "气体", "液体", "未知"] },
  { id: 99, text: "Identify the element with atomic number 99.", textZh: "识别原子序数为 99 的元素。", answer: "Einsteinium (Symbol: Es, State: Solid).", answerZh: "锿（符号：Es，状态：固体）。", options: ["Einsteinium", "Erbium", "Europium", "Einstein"], optionsZh: ["锿", "铒", "铕", "爱因斯坦"] },
  { id: 100, text: "What is the symbol for Fermium?", textZh: "镄的符号是什么？", answer: "Fm (Atomic number 100, State: Solid).", answerZh: "Fm（原子序数 100，状态：固体）。", options: ["Fe", "Fr", "Fm", "F"], optionsZh: ["铁", "钫", "镄", "氟"] },
];
